version: '3.8'

services:
  inkstitch-converter:
    build:
      context: ./inkstitch-converter
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=:99
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
    networks:
      - converter-network

networks:
  converter-network:
    driver: bridge 