[build]
builder = "dockerfile"
dockerfilePath = "inkstitch-converter/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "inkstitch-converter"

[services.env]
PORT = "5000"
DEBIAN_FRONTEND = "noninteractive"
DISPLAY = ":99" 